apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiva
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archiva-server
  template:
    metadata:
      labels:
        app: archiva-server
    spec:
      containers:
        - name: archiva
          image: jefferyb/apache-archiva
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: archiva-service
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: archiva-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31111
